travis:
  secure:
    BINSTAR_TOKEN: mlpbhF85oFSwbEW2XgBWYN6zUlHDGd8FHbLhG48t90BTHVp++YFotQvZwEuPpN8zIDb32pZLTvf+nTwfrwGOskKATCGnDoP6Abk66NPclQMicwqBgX6e1E9I+YtEvDkOkb2D7IDkY5gSE8JShfIXfiOGlCN9g6bx1fNVKlooYfzwotAK8eoF4i3moEYTt+P53+Dl4QLD6YTZWVV2j6cdZxh374vY+mkuXBbFaHNgNMkQMK4rB6rwR7H9sw8x8hlqbJiB5AEUBv0mHpD7nBgB48svSvpA42uk9QkKDFlkld/uvHe9f/7OnYUnbZbvo7X4KIb+jL2D8ZjcUIF8nY517aCVgajD4WuJ5IkJZFgX3iPFkwTi5K5CGzyrwQFI8Su8nCZvKxbQSrtD/mfYeTfLPrYm8dRdrGLXZdXSNRjNwhHDobTifCz7wdHQC25YKrrZUnmLIRGfDDUZktHgIMDrmlrTabaBjT3mRaMPhqr0YXxptDxHw7jVs44QDFFwFCV99FRPoGYcgugZ0DsMuUsQqn0FM1jtU52Ca6kbHfoSY1Hk7skuH1lnQI3FsuQ97rwJienJfrlo91e+JKFJ8JKh/h1XDte9P+/AcG06Br6cmnOyohA8B9didp/ERDH6U5XgRiRtR9/KxcoiDRotpdAbAcQcXhA4MHDQf6OHIUUYTcE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
